---
- name: Allow incoming ssh
  block:
  - iptables: chain=INPUT protocol=tcp match=tcp destination_port=ssh jump=ACCEPT
  - command: netfilter-persistent save

- name: Install fail2ban
  apt: name=fail2ban state=latest
